# Use official Python image as base
FROM python:3.12.2

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /backend

# Create and activate a virtual environment
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Install Streamlit and scikit-learn
RUN pip install streamlit scikit-learn

# Copy the backend source code to the working directory
COPY . .

EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "stream.py"]
