# Generated by Django 5.0.4 on 2024-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_courses', models.IntegerField()),
                ('time_study', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
